---
title: "CCLE"
author: "Sohyeon Kim"
date: "10/18/2020"
output: pdf_document
---

# packages
```{r warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
library(Matrix)
library(data.table)
library(pander)
library(Rcpp)
library(splines)
library(fda)
library(glmnet)

source("https://raw.githubusercontent.com/S0Hye0NKim/add_decomp/master/functions/add_decomp_function.R")
sourceCpp("functions/add_decomp_function.cpp")
```




# 0. Data & Screening


## 0-(1) Screening Y

```{r message = FALSE, warning = FALSE}
Y <- fread("resp_mat.csv")[, -1]
m <- ncol(Y)
trt_nm <- readLines("trt_nm.txt", encoding = "UTF-8") %>%
  str_split(pattern = ",") %>%
  sapply(FUN = function(x) str_remove_all(x, pattern = "'") %>% str_trim) %>%
  unlist()
trt_nm <- trt_nm[trt_nm != ""]
names(Y) <- trt_nm

Y_sd <- Y[, lapply(.SD, sd)] %>% as.matrix %>% t()
data.frame(Y_sd) %>%
  mutate(group = rownames(.)) %>%
  select(group, Y_sd) %>%
  arrange(Y_sd) %>% head(5)

Y <- Y[, -"Panobinostat"] 
m <- ncol(Y)
```

Panobinostat 의 sd = 0.08 -> 제거

## 0-(2) Screening X

### 0-(2)-(1) Standard deviation of X

 * Assumption : Genes with small sd are irrelevant to the drug responses. 

```{r}
X <- fread("express_mat.csv")
cell_name <- X[[1]]
rownames(X) <- cell_name
X <- X[, -1]

X_sd <- X[, lapply(.SD, FUN = sd)] %>% as.matrix() %>% t()
idx_scr_sd <-  data.frame(X_sd) %>%
  mutate(variable = rownames(.)) %>%
  select(variable, X_sd) %>%
  arrange(-X_sd) %>% 
  .[1:10000, ] %>% .$variable

X <- select(X, idx_scr_sd)
```


### 0-(2)-(2) Correlation of X and Y

$$\frac{1}{23}\sum_{g\ne11}|\text{cor}(x_j, y_g)|$$

 * Assumption : Genes having low correlations with drugs may not affect the drug responses. 

```{r}
n <- nrow(X)
p <- 100

idx_scr_cor <- cor(X, Y) %>% abs %>%
  apply(MARGIN = 1, FUN = mean) %>%
  data.frame(variable = names(.), cor = .) %>%
  arrange(-cor) %>% first(p) %>% .$variable

X <- select(X, idx_scr_cor) %>% 
  apply(MARGIN = 2, FUN = function(x) (x - mean(x))/(sd(x)*sqrt((n-1)/n))) %>%
  cbind(1, .)
colnames(X)[1] <- "intercept"
gene_ex <- colnames(X)
```



```{r}
K <- 10
b <- 21
tau_seq <- seq(from = 0.4, to = 0.6, length.out = b)

knots_seq <- seq(min(tau_seq) - 0.02, max(tau_seq) + 0.02, length.out = K)
Phi <- fda::bsplineS(tau_seq, breaks= knots_seq, norder=2, nderiv=0, returnMatrix=FALSE)

V <- calc_V(as.matrix(X), Phi)
```


```{r}
lasso_coef <- matrix(nrow = p+1, ncol = m)
for(g in 1:m) {
  cv.lasso <- cv.glmnet(x = X[, -1], y = as.matrix(Y)[, g], alpha = 1, type.measure = "mae")
  lasso_model <- glmnet(X[, -1], as.matrix(Y)[, g], family = "gaussian", alpha = 1, lambda = cv.lasso$lambda.min)
  lasso_coef[, g] <- c(lasso_model$a0, as.vector(lasso_model$beta))
}


theta_init <- matrix(nrow = (p+1)*K, ncol = m)
for(g in 1:m) {
  for(j in 0:p) {
    theta_init[((j*K)+1):((j+1)*K), g] <- lasso_coef[j+1, g]
  }
}

Y_modified <- (Y - X%*%lasso_coef) %>% as.matrix

lin_model <- lm(Y_modified~., data = data.frame(X[, -1]))
alpha_init <- lin_model$coefficients

```


```{r}
max_iter <- 300
delta <- 1
lambda_1 <- 1.25
lambda_2 <- 0.25
tol_error <- 0.1

start <- Sys.time()
result <- add_decomp(delta, lambda_1, lambda_2, tol_error, max_iter, X = as.matrix(X), Y = as.matrix(Y), 
                     V = V, Phi = Phi, theta_0 = theta_init, alpha_0 = alpha_init)
end <- Sys.time()

end - start
```



```{r}
result$iter_error %>% 
  na.omit() %>%
  data.frame %>%
  mutate(iter = 1:nrow(.)) %>%
  filter(iter > 15) %>% 
  gather(key = "estimator", value = "value", -iter) %>%
  ggplot() +
  geom_line(aes(x = iter, y = value, group = estimator, color = estimator)) +
  facet_wrap(~estimator, scales = "free_y")
```

```{r}
sing_val <- svd(result$alpha)$d
sum(sing_val[1:1])/sum(sing_val)
rankMatrix(result$alpha)
```

```{r}
gamma_hat <- est_gamma(Phi = Phi, theta = result$theta)
```







```{r}
data.frame(col = rep(1:m, each = (p+1)), 
           row = rep(1:(p+1), m),
           value = as.vector(gamma_hat[[3]])) %>%
  mutate(value = ifelse(abs(value) < 0.1^5, 0, value)) %>%
  ggplot(aes(x = col, y = -row, fill = value)) +
  geom_tile(color = "grey") +
  scale_fill_gradient2(low = "red",mid = "white", high = "blue") +
  theme_bw() +
  theme(axis.line = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(), 
    axis.title.x = element_blank(), 
    axis.text.x = element_blank(), 
    axis.ticks.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank()) +
  ggtitle(expression(Gamma~"("~tau[3]~"=0.5)"))
```

```{r}
gamma_hat <- est_gamma(Phi, theta = result$theta)

lapply(gamma_hat, FUN = function(x) data.frame(col = rep(1:m, each = (p+1)),
                                                   row = rep(1:(p+1), m),
                                                   value = as.vector(x))) %>%
  `names<-`(tau_seq) %>%
  bind_rows(.id = "tau") %>%
  mutate(is_nonzero = ifelse(abs(value) < 0.1^5, 0, 1)) %>%
  group_by(col, row) %>%
  summarise(is_nonzero = mean(is_nonzero)) %>%
  mutate(is_nonzero = ifelse(is_nonzero == 0, 0, 1) %>% as.character) %>%
  ggplot(aes(x = col, y = -row, fill = is_nonzero)) +
  geom_tile(color = "grey") +
  scale_fill_manual(values = c("white", "black")) + 
  theme_bw() +
  theme(axis.line = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(), 
    axis.title.x = element_blank(), 
    axis.text.x = element_blank(), 
    axis.ticks.x = element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank()) +
  ggtitle(expression("all of"~Gamma~"("~tau[l]~")"))
```

```{r}
idx_nz_est <- lapply(gamma_hat, FUN = function(x) which(abs(x) > 0.1^5, arr.ind = TRUE) %>% as_tibble) %>%
    bind_rows (.id = "tau") %>%
    group_by(row, col) %>%
    summarise(zero = n()) 

gamma_hat %>%
  lapply(FUN = function(x) x[idx_nz_est$row, idx_nz_est$col] %>% diag %>%
           data.frame(row = idx_nz_est$row, col = idx_nz_est$col, value = . )) %>%
  `names<-`(value = tau_seq) %>%
  bind_rows(.id = "tau") %>%
  filter(row == 50) %>% 
  unite(col = index, row, col, sep = ",") %>%
  mutate(index = paste0("(", index, ")"), tau = as.numeric(tau)) %>%
  ggplot() +
  geom_line(aes(x = tau, y = value, group = index, color = index), size = 1.2) +
  labs(x = expression(tau[l]), title = expression(gamma~"("~tau[l]~"), b = 21, "~Delta~"=[0.4,0.6]"))
```



# Check loss sum

$$\sum_\ell^{b}\sum_{g=1}^m\sum_{i=1}^n\frac{1}{n}\rho_\tau(Y_i^{(g)}-x_i^T[\alpha^{(g)}+\gamma^{(g)}(\tau)])\\=\sum_\ell^{b}\sum_{g=1}^m\sum_{i=1}^n\frac{1}{n}\rho_\tau(e_i^{(\ell)(g)})$$


```{r}
cal_cl_sum(result$e, tau_seq)
```

```{r}
est_beta <- lapply(gamma_hat, FUN = function(x) x + result$alpha)
est_e <- lapply(est_beta, FUN = function(x) as.matrix(Y) - X %*% x)

cal_cl_sum(est_e, tau_seq)
  
```



```{r}
Y_list <- list()
for(i in 1:length(tau_seq)) {
  Y_list[[i]] <- as.matrix(Y)
}

cal_cl_sum(Y_list, tau_seq)
```




# various lambda_1

```{r}
lamb_1_seq <- seq(from = 0, to = 0.05, by = 0.01) %>% c(seq(from = 0.1, to = 1, by = 0.1), 2, 4, 6)
simul_lamb1 <- list()

for(idx in 1:length(lamb_1_seq)) {
  simul_lamb1[[idx]] <- add_decomp(delta = 1, lambda_1 = lamb_1_seq[idx], lambda_2 = 1.5,
                                   tol_error = 0.1, max_iter = 300, 
                                   X = as.matrix(X), Y = as.matrix(Y), V = V, Phi = Phi)
  if((idx %% 2) == 1) print(paste0("iter = ", idx))
}
```

```{r}
alpha_hat <- simul_lamb1 %>% lapply(FUN = function(x) x$alpha)

lapply(alpha_hat, FUN = function(x) svd(x) %>% .$d) %>%
  lapply(FUN = function(x) data.frame("ratio" = (sum(x[1])/sum(x)), rank = sum(abs(x) > 0.1^5))) %>%
  `names<-`(value = lamb_1_seq) %>%
  bind_rows(.id = "lambda1") %>%
  ggplot() +
  geom_line(aes(x = lambda1, y = ratio, group = 1)) +
  labs(title = expression("1st singular value / sum of singular values "~lambda[2]~"=1.5 "~delta~"=1, max iter = 300")) +
  xlab(label = expression(lambda[1]))
```


```{r}
simul_lamb1 %>% lapply(FUN = function(x) x$theta %>% est_gamma(Phi = Phi, theta = .) %>% .[[3]]) %>%
  lapply(FUN = function(x) svd(x) %>% .$d) %>%
  lapply(FUN = function(x) data.frame(sigma_1 = x[1], sigma_2 = x[2], sigma_3 = x[3], 
                                      ratio = sum(x[1:3])/sum(x))) %>%
  `names<-`(value = lamb_1_seq) %>%
  bind_rows(.id = "lambda_1")
```


```{r}
alpha_hat %>%
  lapply(FUN = function(x) svd(x) %>% .$d %>% .[1:2] ) %>%
  lapply(FUN = function(x) data.frame(t(x))) %>%
  `names<-`(value = lamb_1_seq) %>%
  bind_rows(.id = "lambda_1") %>%
  `names<-`(value = c("lambda_1", "first", "second")) %>%
  gather(data = ., key = "sing_val", value = value, -lambda_1) %>%
  ggplot() +
  geom_line(aes(x = lambda_1, y = value, group = sing_val, color = sing_val)) +
  facet_wrap(~sing_val, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



# various lambda_2

```{r}
lamb_2_seq <- c(seq(from = 0.1, to = 2, by = 0.1), seq(2.5, 5, by = 0.5))
simul_lamb2 <- list()

for(idx in 1:length(lamb_2_seq)) {
  simul_lamb2[[idx]] <- add_decomp(delta = 1, lambda_1 = 1, lambda_2 = lamb_2_seq[idx],
                                   tol_error = 0.1, max_iter = 300, 
                                   X = as.matrix(X), Y = as.matrix(Y), V = V, Phi = Phi)
  if((idx %% 2) == 1) print(paste0("iter = ", idx))
}
```



```{r}
cal_zero <- function(gamma, b) {
  data <- lapply(gamma, FUN = function(x) which(abs(x) < 0.1^5, arr.ind = TRUE) %>% as_tibble) %>%
  `names<-`(value= tau_seq) %>%
  bind_rows(.id = "tau") %>% 
  group_by(row, col) %>%
    summarise(zero = n()) %>%
    filter(zero == b)
  return(nrow(data))
}
```

```{r}
gamma_hat <- simul_lamb2 %>%
  lapply(FUN = function(x) x$theta) %>%
  lapply(FUN = function(x) est_gamma(Phi = Phi, theta = x))

gamma_hat %>%
  lapply(FUN = function(x) cal_zero(gamma = x, b = b) %>% data.frame(zero_count = .)) %>%
  `names<-`(value = lamb_2_seq) %>%
  bind_rows(.id = "lambda_2") %>%
  mutate(ratio = zero_count/((p+1)*m)) %>%
  ggplot() +
  geom_line(aes(x = lambda_2, y = ratio, group = 1)) +
  xlab(label = expression(lambda[2])) +
  labs(title = expression("# of zero entry/total entry"~lambda[1]~"=1, "~delta~"=1, max iter = 300"))
```

```{r}
extr_e <- simul_lamb2 %>%
  lapply(FUN = function(x) x$e) 

cl_sum <- list()
for(i in 1:length(lamb_2_seq)) {
  cl_sum[[i]] <- data.frame(cl_sum = cal_cl_sum(e = extr_e[[i]], tau_seq = tau_seq))
}
```

```{r}
cl_sum %>%
  `names<-`(value = lamb_2_seq) %>%
  bind_rows(.id = "lambda_2") %>%
  ggplot() +
  geom_line(aes(x = lambda_2, y = cl_sum, group = 1))
```


# Two way

```{r}
lamb_1_seq <- seq(from = 0.25, to = 2, by = 0.25)
lamb_2_seq <- seq(from = 0.25, to = 2, by = 0.25)


simul_2_way <- list()
for(idx_1 in 1:length(lamb_1_seq)) {
  simul_2_way[[idx_1]] <- list()
  for(idx_2 in 1:length(lamb_2_seq)) {
    simul_2_way[[idx_1]][[idx_2]] <- add_decomp(delta = 1, lambda_1 = lamb_1_seq[idx_1], 
                                                lambda_2 = lamb_2_seq[idx_2], tol_error = 0.1, 
                                                max_iter = 300, X = as.matrix(X), Y = as.matrix(Y), 
                                                V = V, Phi = Phi)
  }
}
```


```{r}
simul_2_way %>%
  lapply(FUN = function(x) lapply(x, FUN = function(y) cal_cl_sum(e = y$e, tau_seq = tau_seq) %>% data.frame(cl_sum = .))) %>%
  lapply(FUN = function(x) x %>% `names<-`(value= lamb_2_seq) %>% bind_rows(.id = "lambda_2")) %>%
  `names<-`(value = lamb_1_seq) %>%
  bind_rows(.id = "lambda_1") %>%
  ggplot() +
  geom_tile(aes(x = lambda_1, y = lambda_2, fill = cl_sum)) +
  labs(title = "check loss sum when max iter = 300")
```






























